const dotenv = require('dotenv');
dotenv.config();

module.exports = {
	BASE_URL: process.env.BASE_URL,
	API_VERSION: process.env.API_VERSION,
	SERVER: process.env.SERVER,
	JWT_SECRET: process.env.JWT_SECRET,
	JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
	JWT_TOKEN_LIFE: process.env.JWT_TOKEN_LIFE,
	JWT_REFRESH_TOKEN_LIFE: process.env.JWT_REFRESH_TOKEN_LIFE,
	WEB_API_KEY: process.env.WEB_API_KEY,
	PWD_SECRET: process.env.PWD_SECRET,
	SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
	SENDGRID_EMAIL_FROM: process.env.SENDGRID_EMAIL_FROM,
	EMAIL_SIGNIN_URL: process.env.EMAIL_SIGNIN_URL,
	FILE_LOCATION: process.env.FILE_LOCATION,
	VERIFICATION_URL: process.env.VERIFICATION_URL,

	// TWILIO
	TWILIO_SID: process.env.TWILIO_SID,
	TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
	TWILIO_SMS_MUMBER: process.env.TWILIO_SMS_MUMBER,

	// AWS
	AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
	AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
	AWS_REGION: process.env.AWS_REGION,
	AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
	AWS_FILE_PERMISSION: process.env.AWS_FILE_PERMISSION,
	AWS_END_POINT: process.env.AWS_END_POINT,
	AWS_PROFILE_PICTURES_FOLDER: process.env.AWS_PROFILE_PICTURES_FOLDER,
	AWS_KYC_DOCUMENTS_FOLDER: process.env.AWS_KYC_DOCUMENTS_FOLDER,
	APP_URL: process.env.APP_URL,

};
